# Generated by Django 5.2.4 on 2025-11-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
    ]
