# Generated by Django 5.2.4 on 2025-11-16 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20251116_1921'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['order'], 'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.AddField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show/hide feature'),
        ),
        migrations.AddField(
            model_name='feature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(help_text='Detailed feature description'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='SVG icon or icon name', null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(help_text='Feature title', max_length=100),
        ),
        migrations.CreateModel(
            name='SuggestedFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('votes', models.IntegerField(default=1)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suggested Feature',
                'verbose_name_plural': 'Suggested Features',
                'ordering': ['-votes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Task description', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Task priority level', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='pending', help_text='Task status', max_length=15)),
                ('due_date', models.DateTimeField(blank=True, help_text='Due date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='todo_todo_user_id_54a3c3_idx'), models.Index(fields=['status'], name='todo_todo_status_90d961_idx')],
            },
        ),
    ]
